<a href="https://colab.research.google.com/github/shivam2898-data/Python_projects/blob/main/numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Introduction to Numpy**

In [ ]:
# Numpy is an open source library that is used for handle for scintific calculation.
# why numpy is better than a list?
# 1.numpy --->Homogeneous data type,   List ---->Hetrogeneous data type
# 2.memory consumption ---->less, High(List)
# 3.time consumption ---->less(numpy),  High(list)

In [ ]:
!pip install numpy

import numpy as np

In [ ]:
a=[1,34,67,90]
b=np.array(a)
b
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
print("total shape=", b.shape)    ##shape= n(rows)  , n(colums)
print("total element=", b.size)   ## size= n(rows)* n(colums)
print("total dimension=", b.ndim) ##ndim= number of dimension


total shape= (4,)
total element= 4
total dimension= 1


In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print("total shape=", b.shape)    ##shape= n(rows)  , n(colums)
print("total element=", b.size)   ## size= n(rows)* n(colums)
print("total dimension=", b.ndim) ##ndim= number of dimension

total shape= (3, 3)
total element= 9
total dimension= 2


In [ ]:
# row_1=[1,2,3]
# row_2=[4,5,6]
# row_3=[7,8,9]

# colum_1=[1,4,7]
# colum_1=[2,5,8]
# colum_1=[3,6,9]

## **User defined Array**

In [ ]:
a=[]
size=int(input("enter size: "))
for i in range(size):
  val=int(input("enter item: "))
  a.append(val)
b=np.array(a)
b

enter size: 3
enter item: 23
enter item: 56
enter item: 89


array([23, 56, 89])

## **Pre-defined function in Numpy**

In [ ]:
# 1. zeros()----> this is pre defined functions of numpy that will return all the values 0 in either one dimensional or multi-dimensional
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [ ]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 2.ones()----> this is also pre defined function of numpy and it will return all the values as 1.
a=np.ones(3)
a

array([1., 1., 1.])

In [ ]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Images---> Pixels(0-255)----> black&white images= height,width
#colourful_images=height  ,width,  color_channel(red,gree,blue)
# Machine learning---> actual_answer , Prediction_answer ---> optimization technique(m,b)

In [ ]:
# 3.eye()--->It will create an array in which digonal positional elements are 1 and rest all are 0.

a=np.eye(3)   ##Symmatric Matix= n(r)=n(c)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.eye(3,4)    ##Asymmatric Matrix= n(r) !=n(c)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# 4 diag()----> it will create an array in which we can set digonal positional elements.

a=np.array([1,34,67,90])
a
b=np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 90]])

In [ ]:
# 5. random module

#a). Randint()----> randint(min_range, max_range, total_numbers)

a=np.random.randint(1,10,3)
a

array([8, 9, 1])

In [ ]:
#b). Rand()----> it will generate random number in range 0-1.
a=np.random.rand(4)
a

array([0.90268704, 0.16145082, 0.92144004, 0.45713462])

In [ ]:
a=np.random.rand(2,3)
a

array([[0.1821002 , 0.78714028, 0.51769166],
       [0.16494994, 0.30997187, 0.09030248]])

In [ ]:
#c). seed()----> it will fix our random generated data.

np.random.seed(45)   # compulsory to pass an argument.
a=np.random.randint(1,10,3)
a

array([4, 1, 6])

In [ ]:
##view and copy


#view---> modification in original data.
#copy---> changes in duplicate entries.

a=np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#view
b=a[3:6]
b[:]=0
b
a

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

In [ ]:
#copy
a=np.array([10,20,30,40,50,60,70,80,90])
b=a[3:6].copy()
b[:]=0
b
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

## **Conditional Selection in Numpy**

In [ ]:
#arange()
a=np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

## **Reshaping the Array**

In [ ]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b=np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a*b  ##wrong

array([[ 5, 12],
       [21, 32]])

In [ ]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [ ]:
a=np.random.randint(1,50,12)
a

array([36,  5, 16,  2, 15,  9, 24, 47,  9, 13, 35, 25])

In [ ]:
#1*12 ,12*1
#2*6, 6*2
#3,4 4*3

In [ ]:
a.reshape(2,6)

array([[36,  5, 16,  2, 15,  9],
       [24, 47,  9, 13, 35, 25]])

In [ ]:
a.reshape(3,4)

array([[36,  5, 16,  2],
       [15,  9, 24, 47],
       [ 9, 13, 35, 25]])

In [ ]:
a.reshape(6,2)

array([[36,  5],
       [16,  2],
       [15,  9],
       [24, 47],
       [ 9, 13],
       [35, 25]])

In [ ]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(a)

45

In [ ]:
np.sum(a, axis=0)   ##axis=0 column wise

array([12, 15, 18])

In [ ]:
np.sum(a, axis=1) #axis=1 row wise operation


array([ 6, 15, 24])

In [ ]:
# Unique()---> it will create an array in which we have unique values.
#return 3 array
#1). arr---->unique array
#2). return_index=True----> unique values indexing
#3). return_counts=True----> unique values frequency


In [ ]:
a=np.array([1,2,3,4,1,1,1,1,3,4,5,6,7,7,7,7,7])
a

array([1, 2, 3, 4, 1, 1, 1, 1, 3, 4, 5, 6, 7, 7, 7, 7, 7])

In [ ]:
np.unique(a, return_index=True, return_counts=True)


(array([1, 2, 3, 4, 5, 6, 7]),
 array([ 0,  1,  2,  3, 10, 11, 12]),
 array([5, 1, 2, 2, 1, 1, 5]))

In [ ]:
#linspace()----> it will return same gap values from a given range.
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
#1.25-1=0.25
#1.5-1.25=0.25
#1.75-1.5=0.25
#2-1.75-0.25


In [ ]:
#stacking
#1). hstack()---->
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
np.hstack((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#1). vstack()---->
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
np.vstack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a=np.array([1,56,90])
np.sin(a)

array([ 0.84147098, -0.521551  ,  0.89399666])

In [ ]:
np.cos(a)

array([ 0.54030231,  0.85322011, -0.44807362])

In [ ]:
np.tan(a)

array([ 1.55740772, -0.61127369, -1.99520041])

# 1. create an array using numpy?

In [ ]:
a=[]
size=int(input("enter size: "))
for i in range(size):
  item=int(input("enter item: "))
  a.append(item)
b=np.array(a)
b

enter size: 3
enter item: 10
enter item: 20
enter item: 30


array([10, 20, 30])

## 2.create an array of 10 random integers?

In [ ]:
a=np.random.randint(1,20,10)
a

array([12,  7, 17, 10, 12, 11,  7, 15, 16, 18])

## 3.create an array of elements from 10-20?

In [ ]:
a=np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## 4.create an array which contains value 5,10 times?

In [ ]:
a=[5]*10
b=np.array(a)
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5.create a one dimensional array and convert that into 3*3 matrix?

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
a.reshape(3,3)



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 6.create a 2d array of size 3*3 but all the elements should be between 0 to 1?

In [ ]:
a=np.random.rand(9)
a.reshape(3,3)

array([[0.13011979, 0.21534257, 0.93984369],
       [0.44818824, 0.01356729, 0.8201502 ],
       [0.30277134, 0.33550978, 0.2716822 ]])

## 7.concatenate 2d array horizontally and vertically?


In [ ]:
#horizont
a=([1,2,3])
b=([4,5,6])
np.hstack((a,b))

#vertically
a=([1,2,3])
b=([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
np.hstack((a,b))
#np.vstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])